name = "backend"
compatibility_date = "2024-08-04"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODk1MjhkYTQtOTMxYS00NjQ3LWJlNWQtODkyY2ZmMTNkZDlmIiwidGVuYW50X2lkIjoiNzIwZjQ5YmY2ZWQ3ZDk1MTI4NjA4MWY3YTg2YWU2N2E0ODQ1ZDdiYmNiMWIwNDc5MGJkZmNmMDg5M2NjNDA4MSIsImludGVybmFsX3NlY3JldCI6IjljZDA0Mjg5LWQ2NmQtNDVkMC1iZDY4LTk5MjI2N2Y5ZjA0NyJ9.nL8UOyw0qXfh5L4dDkColOjtdrFyyg7MGIeXyaCB2cU"